# Generated by Django 5.2.7 on 2025-10-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pecas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("quantidade", models.IntegerField(default=0)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=15)),
                ("criado_data", models.DateTimeField(auto_now_add=True)),
                ("atualizado_data", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
